### ISSUE TITLE
Backwards compatibility in 4.0

### ISSUE THREAD

**Issue by kgoggin** [MinimaHQ/re-formality#89]
I've been using the 4.0 beta in a new project, and really loving the PPX approach and how much less boilerplate I have to write - really nice job with that!

I've also got a project with a _lot_ of forms that are currently on v3 API. I'd love to upgrade to v4 to start using the PPX, but don't want to have to upgrade everything in one shot. It _looks_ like you've included the v3 API under FormalityCompat, but I wanted to check if you were planning on shipping that with the v4 final release and, if so, how long you anticipated supporting both APIs.

Thanks!

**Comment by alexfedoseev** [comment]
It will be shipped with v4. I don’t mind keeping it as long as users need it. As a last resort, it can be extracted into a stand-alone package.
