### ISSUE TITLE
Could not resolve  re-formality/ppx

### ISSUE THREAD

**Issue by kivi** [MinimaHQ/re-formality#90]
I am on Windows 10 and I am trying to update old re-formality to the latest one.

``` node_modules/re-reformality/package.json
  "name": "re-formality",
  "version": "4.0.0-beta.7",
```

When I do: `bsb -make-world` I get:

```
Could not resolve  re-formality/ppx in C:\Users\myuser\projectname
Fatal error: exception Failure("re-formality/ppx not found when resolving ppx-flags")
```

**Comment by alexfedoseev** [comment]
Hi, it would require [this change](https://github.com/MinimaHQ/res-logger/blob/master/.github/workflows/scripts/postinstall.js#L35-L43) to be applied to this repo. Will do this within next couple of days.

**Comment by ashutheone** [comment]
Hi @kivi 
We faced a similar problem when we were trying to build in a Docker container. We update the alpine linux version for our container and then we added the latest version of compatible GNU C library version. We ended up making following changes in our Dockerfile which solved this problem for us.

FROM node:12-alpine
`RUN wget -q -O /etc/apk/keys/sgerrand.rsa.pub https://alpine-pkgs.sgerrand.com/sgerrand.rsa.pub
RUN wget https://github.com/sgerrand/alpine-pkg-glibc/releases/download/2.30-r0/glibc-2.30-r0.apk
RUN apk add glibc-2.30-r0.apk`

You can try to do the same for your dev environment. Hope it helps you.

**Comment by alexfedoseev** [comment]
I hope it was fixed for windows users in the latest release I did yesterday. (@kivi Please, let me know) But apparently it broke something on Linux. Not sure why though. @ashutheone can you open another issue? I can't promise I will solve it immediately but at least it will be on my radar.

**Comment by kivi** [comment]
works now on windows.
Version: ^4.0.0-beta.9
